apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-deployment
  labels:
    app: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb        
    spec:
      containers:
      - name: mariadb
        image: lscr.io/linuxserver/mariadb:latest
        ports:
        - containerPort: 3306
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "Europe/Warsaw"
        - name: MYSQL_DATABASE
          value: "bookstack-mariadb"
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bookstack-secret
              key: ROOT_ACCESS_PASSWORD
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: bookstack-secret
              key: DB_USERNAME
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bookstack-secret
              key: DB_PASSWORD
        volumeMounts:
        - name: config
          mountPath: /config
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: mariadb-config-pvc

